[package]
name = "wchangerd"
version = "0.1.0"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]

[dependencies]
toml = "0.1"
quick-error = "0.2"
rustc-serialize = "0.3"
chrono = "0.2"
log = "0.3"
env_logger = "0.3"
docopt = "0.6"
rand = "0.3"
chan-signal = "0.1"
chan = "0.1"
