[common]
endpoint = "127.0.0.1:17345"

[server]
default_playlist = "default"
watch = "1 minute"
# watch = "disabled"
# watch = "auto"  # inotify, in future versions
stats_db = "~/.cache/wcd/stats.db"

[server.defaults]
# mode = "sequential"
mode = "random"
change_every = "5 minutes"
trigger_on_select = true
use_last_on_select = true
command = ["echo", "{}"]

[server.playlists.default]
directories = ["/tmp/wchtest"]
change_every = "1 minute"

[server.playlists.sfw]
directories = ["/tmp/safe"]
mode = "sequential"
use_last_on_select = false

