[package]
name = "wcd"
version = "0.1.0"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]

[dependencies]
wcd-common = { path = "../common" }
log = "0.3"
env_logger = "0.3"
rustc-serialize = "0.3"
chrono = "0.2"
docopt = "0.6"
rand = "0.3"
chan = "0.1"
nanomsg = "0.4"
bincode = "0.4"
