[package]
name = "wcd"
version = "0.2.0"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]

[dependencies]
wcd-common = { path = "../common" }
clap = "2.20"
log = "0.3"
env_logger = "0.3"
chrono = "0.2"
rand = "0.3"
chan = "0.1"
nanomsg = "0.6"
