#files = ["path/to/file-1.jpg", "~/file-2.png"]
#directories = ["path/to/dir-1", "~/dir-2"]
directories = ["/tmp/wchtest"]

# mode = "sequential"
mode = "Random"

command = ["echo", "{}"]

change_every = "5 seconds"
