[package]
name = "wcd-common"
version = "0.2.0"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]

[dependencies]
quick-error = "1.1"
serde = "1.0"
serde_derive = "1.0"
chrono = "0.3"
shellexpand = "1.0"
toml = "0.4"
bincode = { git = "https://github.com/TyOverby/bincode" }
