[package]
name = "wcdctl"
version = "0.2.0"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]

[dependencies]
wcd-common = { path = "../common" }
clap = "2.20"
nanomsg = "0.6"
bincode = "0.6"
chrono = "0.2"
